
POST http://localhost:3003/api/blogs
content-type: application/json

{"title": "Micharl Jordan's 63 point game", "author": "Kevin", "url": "http://www.nba.com", "likes": "10", "userId":"61c50f2e3a96cdd9a5d4a132"}

###
Get http://localhost:3003/api/blogs
content-type: application/json

###
POST http://localhost:3003/api/blogs
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdvYXQyMyIsImlkIjoiNjFjNTBmMmUzYTk2Y2RkOWE1ZDRhMTMyIiwiaWF0IjoxNjQwMzA5NTEzLCJleHAiOjE2NDAzMTEzMTN9.G-Q2w20mcGfJRGkxjyT-oPN4ho9XFuGz8KUM5kNZRso

{"title": "Micharl Jordan's 45 point game", "author": "Woj", "url": "http://www.nba.com", "likes": "10"}

###
POST http://localhost:3003/api/blogs
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhdmV5MDMiLCJpZCI6IjYxYzUyNGEyNWJkNDBjZWU5NmFkZjE3ZCIsImlhdCI6MTY0MDMwOTk3MiwiZXhwIjoxNjQwMzExNzcyfQ.NAyXowMwZ14LSN2JxmuGavJxKhcEksJtPdDamIwYLTg

{"title": "Kobe Bryant's 81 point game", "author": "Kevin", "url": "http://reddit.com", "likes": "400"}

####
delete http://localhost:3003/api/blogs/61c525305bd40cee96adf185
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhdmV5MDMiLCJpZCI6IjYxYzUyNGEyNWJkNDBjZWU5NmFkZjE3ZCIsImlhdCI6MTY0MDMxMTQ2MywiZXhwIjoxNjQwMzEzMjYzfQ.4SQEiX3xXcUZhJZ_Sf5HjiNRXWlkI4M4K2L02edmorY


###
Get http://localhost:3003/api/blogs
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhdmV5MDMiLCJpZCI6IjYxYzUyNGEyNWJkNDBjZWU5NmFkZjE3ZCIsImlhdCI6MTY0MDMxMjY4MiwiZXhwIjoxNjQwMzE0NDgyfQ.rMi6oBJCExNGCBMtyP7qg972IigKQEm0eP1fDIOLutE